version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: sms_protection_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sms_protection_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      app.database.url: "jdbc:postgresql://db:5432/sms_protection_db"
      app.database.username: "admin"
      app.database.password: "test"
    depends_on:
      - db
volumes:
  postgres_data:
