# Database configuration
app.database.url=jdbc:postgresql://localhost:5432/sms_protection_db
app.database.username=admin
app.database.password=test

# Web client configuration
app.web-client.apiKey=api-key
app.web-client.url=url

# Risk configuration
app.acceptableRisk=SAFE
